# Generated by Django 3.0.7 on 2020-07-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportmode',
            old_name='tetha',
            new_name='theta',
        ),
    ]
