# Generated by Django 3.0.7 on 2020-06-28 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20200628_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='scene',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage.Scene'),
        ),
    ]
