# Generated by Django 3.0.7 on 2020-07-01 22:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20200701_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportmode',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
