# Generated by Django 3.0.7 on 2020-06-28 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20200628_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportnetwork',
            name='scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.Scene'),
            preserve_default=False,
        ),
    ]
