# Generated by Django 3.0.7 on 2020-07-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_transportmode_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationresultpermode',
            name='optimization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Optimization'),
        ),
    ]
