# Generated by Django 3.0.7 on 2020-06-29 14:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_transportnetwork_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='demand_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
    ]
