# Generated by Django 3.0.7 on 2020-07-04 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20200704_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportnetwork',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
