# Generated by Django 3.0.7 on 2020-07-05 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_transportnetwork_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
