# Generated by Django 3.0.7 on 2020-06-30 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_city_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('7470e293-327d-4fbf-86b1-debaf5291b09')),
        ),
        migrations.AlterField(
            model_name='city',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('01def6c6-69ca-4b47-b302-07f30e337a69')),
        ),
    ]
