# Generated by Django 3.1 on 2020-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_route_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='n',
            field=models.IntegerField(null=True),
        ),
    ]
