# Generated by Django 3.1 on 2020-08-17 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20200811_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='demand_matrix',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
