# Generated by Django 3.1 on 2020-08-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_transportmode_f_ini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='name',
        ),
    ]
