# Generated by Django 3.1 on 2020-08-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20200818_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportmode',
            old_name='b_a',
            new_name='bya',
        ),
    ]
