# Generated by Django 3.1 on 2020-08-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20200821_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportmode',
            old_name='f_ini',
            new_name='fini',
        ),
        migrations.RenameField(
            model_name='transportmode',
            old_name='f_max',
            new_name='fmax',
        ),
        migrations.RenameField(
            model_name='transportmode',
            old_name='k_max',
            new_name='kmax',
        ),
    ]
