# Generated by Django 3.1 on 2020-10-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20200821_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.IntegerField(choices=[(1, 'CUSTOM'), (2, 'PREDEFINED'), (3, 'CIRCULAR')], default=1),
            preserve_default=False,
        ),
    ]
