# Generated by Django 3.1 on 2020-10-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_route_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('transport_network', 'name')},
        ),
    ]
