# Generated by Django 3.1 on 2020-10-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_auto_20201002_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='node_sequence_i',
            new_name='nodes_sequence_i',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='node_sequence_r',
            new_name='nodes_sequence_r',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='stop_sequence_i',
            new_name='stops_sequence_i',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='stop_sequence_r',
            new_name='stops_sequence_r',
        ),
    ]
