# Generated by Django 3.1 on 2020-10-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_auto_20201002_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportnetwork',
            name='optimization_ran_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transportnetwork',
            name='optimization_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('finished', 'Finished'), ('error', 'Error')], default=None, max_length=20, null=True),
        ),
    ]
