# Generated by Django 3.1 on 2020-10-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_auto_20201002_1910'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportmode',
            unique_together={('scene', 'name')},
        ),
    ]
