# Generated by Django 3.1 on 2020-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_auto_20201002_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresultperroutedetail',
            name='direction',
            field=models.CharField(choices=[('i', 'going'), ('r', 'reverse')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
