# Generated by Django 3.1 on 2020-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_optimizationresultperroutedetail_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportnetwork',
            name='optimization_error_message',
            field=models.TextField(default=None, null=True),
        ),
    ]
