# Generated by Django 3.1 on 2020-10-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0021_auto_20201005_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportnetwork',
            name='optimization_duration',
            field=models.DurationField(default=None, null=True),
        ),
    ]
