# Generated by Django 3.1 on 2020-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_transportnetwork_optimization_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='nodes_sequence_i',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops_sequence_i',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
