# Generated by Django 3.1 on 2020-10-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_auto_20201008_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportnetwork',
            name='job_id',
            field=models.UUIDField(null=True),
        ),
    ]
