# Generated by Django 3.1 on 2020-10-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0024_transportnetwork_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationresultperroute',
            name='frequency_per_line',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
