# Generated by Django 3.1 on 2020-11-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0025_optimizationresultperroute_frequency_per_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='angles',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='etha',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='etha_zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='gi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='hi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
