# Generated by Django 3.1.3 on 2020-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0026_auto_20201105_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationresultperroutedetail',
            name='direction',
            field=models.CharField(choices=[('direction_1', 'going'), ('direction_2', 'reverse')], max_length=11),
        ),
    ]
